age=c(1,2,3,4,5)
time=c(10,20,30,40,55)
lbls=c("a","b","c","d","e")
pie(age,labels=lbls,col=c("red","blue","yellow","green","black"), main = "age piechart")
summary(age,time)
summary (age)
summary (time)
boxplot(age,time)
barplot(age)
lbl=c("ade","bet","cat","din","eto")
barplot(age,col=c("red","blue","green","yellow","black"), height=c(10,20,30,40,50))
boxplot(age)
boxplot(time)
barplot(time,col=c("red","blue","black"))
plot(age,time,col=c("black"))